
-- 0- Criação da tabela tratada a partir da base bruta, para maior segurança

	SELECT
		NU_INSCRICAO      AS ID,
		SG_UF_PROVA       AS UF_PROVA,
		SG_UF_ESC         AS UF_ESCOLA,
		TP_ESCOLA         AS TIPO_ESCOLA,
		TP_COR_RACA       AS COR_RACA,
		Q006              AS FAIXA_DE_RENDA,
		Q025              AS INTERNET,
		NU_NOTA_CN        AS NOTA_CIENCIAS_NATUREZA,
		NU_NOTA_CH        AS NOTA_CIENCIAS_HUMANAS,
		NU_NOTA_LC        AS NOTA_LINGUAGENS,
		NU_NOTA_MT        AS NOTA_MATEMATICA,
		NU_NOTA_REDACAO   AS NOTA_REDACAO,
		TP_PRESENCA_CH    AS PRESENCA_CIENCIAS_HUMANAS,
		TP_PRESENCA_CN    AS PRESENCA_CIENCIAS_NATUREZA,
		TP_PRESENCA_MT    AS PRESENCA_MATEMATICA,
		TP_PRESENCA_LC    AS PRESENCA_LINGUAGENS,
		IN_TREINEIRO      AS TREINEIRO
	INTO ENEM_2023_TRATADO
	FROM ENEM_2023_DADOS_BRUTOS;
	
	-- Consulta de validação da tabela ENEM_2023_TRATADO

	SELECT TOP(100)
		*
    FROM 
		ENEM_2023_TRATADO
        

--	1- Remoção de participantes treineiros

	-- Validação antes da exclusão
	SELECT
		COUNT(*) AS Total_Treineiros
	FROM ENEM_2023_TRATADO
	WHERE TREINEIRO = 1;


	BEGIN TRANSACTION;

		DELETE FROM ENEM_2023_TRATADO
		WHERE TREINEIRO = 1;

		SELECT
			@@ROWCOUNT AS Registros_Removidos_Treineiros;

	-- Após validar o resultado:
	COMMIT;
	-- ROLLBACK;

-- 2- Remoção de participantes eliminados
	
	-- Validação antes da exclusão
	SELECT
		COUNT(*) AS Total_Eliminados
	FROM ENEM_2023_TRATADO
	WHERE PRESENCA_CIENCIAS_HUMANAS = 2
	   OR PRESENCA_CIENCIAS_NATUREZA = 2
	   OR PRESENCA_MATEMATICA = 2
	   OR PRESENCA_LINGUAGENS = 2;


	BEGIN TRANSACTION;

		DELETE FROM ENEM_2023_TRATADO
		WHERE PRESENCA_CIENCIAS_HUMANAS = 2
		   OR PRESENCA_CIENCIAS_NATUREZA = 2
		   OR PRESENCA_MATEMATICA = 2
		   OR PRESENCA_LINGUAGENS = 2;

		SELECT
			@@ROWCOUNT AS Registros_Removidos_Eliminados;

	-- Após validar o resultado:
	COMMIT;
	-- ROLLBACK;


-- 3- Remoção de participantes com nota zero em todas as áreas
	
	-- Validação antes da exclusão
	SELECT
		COUNT(*) AS Total_Nota_Zero_Todas_Objetivas
	FROM ENEM_2023_TRATADO
	WHERE NOTA_CIENCIAS_HUMANAS = 0
	  AND NOTA_CIENCIAS_NATUREZA = 0
	  AND NOTA_MATEMATICA = 0
	  AND NOTA_LINGUAGENS = 0;


	BEGIN TRANSACTION;

		DELETE FROM ENEM_2023_TRATADO
		WHERE NOTA_CIENCIAS_HUMANAS = 0
		  AND NOTA_CIENCIAS_NATUREZA = 0
		  AND NOTA_MATEMATICA = 0
		  AND NOTA_LINGUAGENS = 0;

		SELECT
			@@ROWCOUNT AS Registros_Removidos_Prova_Zero;

	-- Após validar o resultado:
	COMMIT;
	-- ROLLBACK;


-- 4- Validação das respostas socioeconômicas
	
	-- Validação antes da exclusão
	SELECT
		COUNT(*) AS Total_Sem_Resposta_Socioeconomica
	FROM ENEM_2023_TRATADO
	WHERE FAIXA_DE_RENDA IS NULL
	   OR INTERNET IS NULL;


	BEGIN TRANSACTION;

		DELETE FROM ENEM_2023_TRATADO
		WHERE FAIXA_DE_RENDA IS NULL
		   OR INTERNET IS NULL;

		SELECT
			@@ROWCOUNT AS Registros_Removidos_Respostas_Socioeconomicas;

	-- Após validar o resultado:
	COMMIT;
	-- ROLLBACK;

		
-- 5- Verificação de registros duplicados
	
	SELECT
		ID,
		COUNT(*) AS Quantidade_Duplicidades
	FROM ENEM_2023_TRATADO
	GROUP BY
		ID
	HAVING
		COUNT(*) > 1;

	-- Nenhuma duplicidade identificada.


-- 6-  Correção de notas importadas em escala incorreta

	-- Validação inicial das notas
	SELECT
		MAX(NOTA_CIENCIAS_NATUREZA) AS Maior_Nota_CN,
		MIN(NOTA_CIENCIAS_NATUREZA) AS Menor_Nota_CN,
		AVG(NOTA_CIENCIAS_NATUREZA) AS Media_Nota_CN,

		MAX(NOTA_CIENCIAS_HUMANAS) AS Maior_Nota_CH,
		MIN(NOTA_CIENCIAS_HUMANAS) AS Menor_Nota_CH,
		AVG(NOTA_CIENCIAS_HUMANAS) AS Media_Nota_CH,

		MAX(NOTA_LINGUAGENS) AS Maior_Nota_LC,
		MIN(NOTA_LINGUAGENS) AS Menor_Nota_LC,
		AVG(NOTA_LINGUAGENS) AS Media_Nota_LC,

		MAX(NOTA_MATEMATICA) AS Maior_Nota_MT,
		MIN(NOTA_MATEMATICA) AS Menor_Nota_MT,
		AVG(NOTA_MATEMATICA) AS Media_Nota_MT
	FROM ENEM_2023_TRATADO;


	BEGIN TRANSACTION;

		UPDATE ENEM_2023_TRATADO
		SET NOTA_CIENCIAS_NATUREZA =
			CASE
				WHEN NOTA_CIENCIAS_NATUREZA > 1000 THEN NOTA_CIENCIAS_NATUREZA / 10
				ELSE NOTA_CIENCIAS_NATUREZA
			END;

		UPDATE ENEM_2023_TRATADO
		SET NOTA_MATEMATICA =
			CASE
				WHEN NOTA_MATEMATICA > 1000 THEN NOTA_MATEMATICA / 10
				ELSE NOTA_MATEMATICA
			END;

		UPDATE ENEM_2023_TRATADO
		SET NOTA_CIENCIAS_HUMANAS =
			CASE
				WHEN NOTA_CIENCIAS_HUMANAS > 1000 THEN NOTA_CIENCIAS_HUMANAS / 10
				ELSE NOTA_CIENCIAS_HUMANAS
			END;

		UPDATE ENEM_2023_TRATADO
		SET NOTA_LINGUAGENS =
			CASE
				WHEN NOTA_LINGUAGENS > 1000 THEN NOTA_LINGUAGENS / 10
				ELSE NOTA_LINGUAGENS
			END;

	-- Após validar o resultado:
	COMMIT;
	-- ROLLBACK;


	-- Validação Final das notas
	SELECT
		MAX(NOTA_CIENCIAS_NATUREZA) AS Maior_Nota_CN,
		MIN(NOTA_CIENCIAS_NATUREZA) AS Menor_Nota_CN,
		AVG(NOTA_CIENCIAS_NATUREZA) AS Media_Nota_CN,

		MAX(NOTA_CIENCIAS_HUMANAS) AS Maior_Nota_CH,
		MIN(NOTA_CIENCIAS_HUMANAS) AS Menor_Nota_CH,
		AVG(NOTA_CIENCIAS_HUMANAS) AS Media_Nota_CH,

		MAX(NOTA_LINGUAGENS) AS Maior_Nota_LC,
		MIN(NOTA_LINGUAGENS) AS Menor_Nota_LC,
		AVG(NOTA_LINGUAGENS) AS Media_Nota_LC,

		MAX(NOTA_MATEMATICA) AS Maior_Nota_MT,
		MIN(NOTA_MATEMATICA) AS Menor_Nota_MT,
		AVG(NOTA_MATEMATICA) AS Media_Nota_MT
	FROM ENEM_2023_TRATADO;
